name: Check branch conformity
on:
  push:

jobs:
  prevent-fixup-commits:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: prevent fixup commits
          run: |
            git fetch origin
            git status
            git log --pretty=format:%s origin/main..HEAD | grep -ie '^fixup\|^wip' && exit 1 || true
